// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/event.proto

package event

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type EventList struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventList) Reset()         { *m = EventList{} }
func (m *EventList) String() string { return proto.CompactTextString(m) }
func (*EventList) ProtoMessage()    {}
func (*EventList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{1}
}

func (m *EventList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventList.Unmarshal(m, b)
}
func (m *EventList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventList.Marshal(b, m, deterministic)
}
func (m *EventList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventList.Merge(m, src)
}
func (m *EventList) XXX_Size() int {
	return xxx_messageInfo_EventList.Size(m)
}
func (m *EventList) XXX_DiscardUnknown() {
	xxx_messageInfo_EventList.DiscardUnknown(m)
}

var xxx_messageInfo_EventList proto.InternalMessageInfo

func (m *EventList) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type CreateEventReq struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEventReq) Reset()         { *m = CreateEventReq{} }
func (m *CreateEventReq) String() string { return proto.CompactTextString(m) }
func (*CreateEventReq) ProtoMessage()    {}
func (*CreateEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{2}
}

func (m *CreateEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventReq.Unmarshal(m, b)
}
func (m *CreateEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventReq.Marshal(b, m, deterministic)
}
func (m *CreateEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventReq.Merge(m, src)
}
func (m *CreateEventReq) XXX_Size() int {
	return xxx_messageInfo_CreateEventReq.Size(m)
}
func (m *CreateEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventReq proto.InternalMessageInfo

func (m *CreateEventReq) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CreateEventRes struct {
	// Types that are valid to be assigned to Result:
	//	*CreateEventRes_Event
	//	*CreateEventRes_Error
	Result               isCreateEventRes_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateEventRes) Reset()         { *m = CreateEventRes{} }
func (m *CreateEventRes) String() string { return proto.CompactTextString(m) }
func (*CreateEventRes) ProtoMessage()    {}
func (*CreateEventRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{3}
}

func (m *CreateEventRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEventRes.Unmarshal(m, b)
}
func (m *CreateEventRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEventRes.Marshal(b, m, deterministic)
}
func (m *CreateEventRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEventRes.Merge(m, src)
}
func (m *CreateEventRes) XXX_Size() int {
	return xxx_messageInfo_CreateEventRes.Size(m)
}
func (m *CreateEventRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEventRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEventRes proto.InternalMessageInfo

type isCreateEventRes_Result interface {
	isCreateEventRes_Result()
}

type CreateEventRes_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type CreateEventRes_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateEventRes_Event) isCreateEventRes_Result() {}

func (*CreateEventRes_Error) isCreateEventRes_Result() {}

func (m *CreateEventRes) GetResult() isCreateEventRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CreateEventRes) GetEvent() *Event {
	if x, ok := m.GetResult().(*CreateEventRes_Event); ok {
		return x.Event
	}
	return nil
}

func (m *CreateEventRes) GetError() string {
	if x, ok := m.GetResult().(*CreateEventRes_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateEventRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateEventRes_Event)(nil),
		(*CreateEventRes_Error)(nil),
	}
}

type UpdateEventReq struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEventReq) Reset()         { *m = UpdateEventReq{} }
func (m *UpdateEventReq) String() string { return proto.CompactTextString(m) }
func (*UpdateEventReq) ProtoMessage()    {}
func (*UpdateEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{4}
}

func (m *UpdateEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventReq.Unmarshal(m, b)
}
func (m *UpdateEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventReq.Marshal(b, m, deterministic)
}
func (m *UpdateEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventReq.Merge(m, src)
}
func (m *UpdateEventReq) XXX_Size() int {
	return xxx_messageInfo_UpdateEventReq.Size(m)
}
func (m *UpdateEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventReq proto.InternalMessageInfo

func (m *UpdateEventReq) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type UpdateEventRes struct {
	// Types that are valid to be assigned to Result:
	//	*UpdateEventRes_Event
	//	*UpdateEventRes_Error
	Result               isUpdateEventRes_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UpdateEventRes) Reset()         { *m = UpdateEventRes{} }
func (m *UpdateEventRes) String() string { return proto.CompactTextString(m) }
func (*UpdateEventRes) ProtoMessage()    {}
func (*UpdateEventRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{5}
}

func (m *UpdateEventRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEventRes.Unmarshal(m, b)
}
func (m *UpdateEventRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEventRes.Marshal(b, m, deterministic)
}
func (m *UpdateEventRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEventRes.Merge(m, src)
}
func (m *UpdateEventRes) XXX_Size() int {
	return xxx_messageInfo_UpdateEventRes.Size(m)
}
func (m *UpdateEventRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEventRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEventRes proto.InternalMessageInfo

type isUpdateEventRes_Result interface {
	isUpdateEventRes_Result()
}

type UpdateEventRes_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type UpdateEventRes_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UpdateEventRes_Event) isUpdateEventRes_Result() {}

func (*UpdateEventRes_Error) isUpdateEventRes_Result() {}

func (m *UpdateEventRes) GetResult() isUpdateEventRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *UpdateEventRes) GetEvent() *Event {
	if x, ok := m.GetResult().(*UpdateEventRes_Event); ok {
		return x.Event
	}
	return nil
}

func (m *UpdateEventRes) GetError() string {
	if x, ok := m.GetResult().(*UpdateEventRes_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UpdateEventRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UpdateEventRes_Event)(nil),
		(*UpdateEventRes_Error)(nil),
	}
}

type DeleteEventReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEventReq) Reset()         { *m = DeleteEventReq{} }
func (m *DeleteEventReq) String() string { return proto.CompactTextString(m) }
func (*DeleteEventReq) ProtoMessage()    {}
func (*DeleteEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{6}
}

func (m *DeleteEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventReq.Unmarshal(m, b)
}
func (m *DeleteEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventReq.Marshal(b, m, deterministic)
}
func (m *DeleteEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventReq.Merge(m, src)
}
func (m *DeleteEventReq) XXX_Size() int {
	return xxx_messageInfo_DeleteEventReq.Size(m)
}
func (m *DeleteEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventReq proto.InternalMessageInfo

func (m *DeleteEventReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteEventRes struct {
	// Types that are valid to be assigned to Result:
	//	*DeleteEventRes_Event
	//	*DeleteEventRes_Error
	Result               isDeleteEventRes_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DeleteEventRes) Reset()         { *m = DeleteEventRes{} }
func (m *DeleteEventRes) String() string { return proto.CompactTextString(m) }
func (*DeleteEventRes) ProtoMessage()    {}
func (*DeleteEventRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{7}
}

func (m *DeleteEventRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEventRes.Unmarshal(m, b)
}
func (m *DeleteEventRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEventRes.Marshal(b, m, deterministic)
}
func (m *DeleteEventRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEventRes.Merge(m, src)
}
func (m *DeleteEventRes) XXX_Size() int {
	return xxx_messageInfo_DeleteEventRes.Size(m)
}
func (m *DeleteEventRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEventRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEventRes proto.InternalMessageInfo

type isDeleteEventRes_Result interface {
	isDeleteEventRes_Result()
}

type DeleteEventRes_Event struct {
	Event int64 `protobuf:"varint,1,opt,name=event,proto3,oneof"`
}

type DeleteEventRes_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*DeleteEventRes_Event) isDeleteEventRes_Result() {}

func (*DeleteEventRes_Error) isDeleteEventRes_Result() {}

func (m *DeleteEventRes) GetResult() isDeleteEventRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *DeleteEventRes) GetEvent() int64 {
	if x, ok := m.GetResult().(*DeleteEventRes_Event); ok {
		return x.Event
	}
	return 0
}

func (m *DeleteEventRes) GetError() string {
	if x, ok := m.GetResult().(*DeleteEventRes_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DeleteEventRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DeleteEventRes_Event)(nil),
		(*DeleteEventRes_Error)(nil),
	}
}

type GetEventReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventReq) Reset()         { *m = GetEventReq{} }
func (m *GetEventReq) String() string { return proto.CompactTextString(m) }
func (*GetEventReq) ProtoMessage()    {}
func (*GetEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{8}
}

func (m *GetEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventReq.Unmarshal(m, b)
}
func (m *GetEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventReq.Marshal(b, m, deterministic)
}
func (m *GetEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventReq.Merge(m, src)
}
func (m *GetEventReq) XXX_Size() int {
	return xxx_messageInfo_GetEventReq.Size(m)
}
func (m *GetEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventReq proto.InternalMessageInfo

func (m *GetEventReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetEventRes struct {
	// Types that are valid to be assigned to Result:
	//	*GetEventRes_Event
	//	*GetEventRes_Error
	Result               isGetEventRes_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetEventRes) Reset()         { *m = GetEventRes{} }
func (m *GetEventRes) String() string { return proto.CompactTextString(m) }
func (*GetEventRes) ProtoMessage()    {}
func (*GetEventRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{9}
}

func (m *GetEventRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventRes.Unmarshal(m, b)
}
func (m *GetEventRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventRes.Marshal(b, m, deterministic)
}
func (m *GetEventRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventRes.Merge(m, src)
}
func (m *GetEventRes) XXX_Size() int {
	return xxx_messageInfo_GetEventRes.Size(m)
}
func (m *GetEventRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventRes proto.InternalMessageInfo

type isGetEventRes_Result interface {
	isGetEventRes_Result()
}

type GetEventRes_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type GetEventRes_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetEventRes_Event) isGetEventRes_Result() {}

func (*GetEventRes_Error) isGetEventRes_Result() {}

func (m *GetEventRes) GetResult() isGetEventRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetEventRes) GetEvent() *Event {
	if x, ok := m.GetResult().(*GetEventRes_Event); ok {
		return x.Event
	}
	return nil
}

func (m *GetEventRes) GetError() string {
	if x, ok := m.GetResult().(*GetEventRes_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetEventRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetEventRes_Event)(nil),
		(*GetEventRes_Error)(nil),
	}
}

type ListEventReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEventReq) Reset()         { *m = ListEventReq{} }
func (m *ListEventReq) String() string { return proto.CompactTextString(m) }
func (*ListEventReq) ProtoMessage()    {}
func (*ListEventReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{10}
}

func (m *ListEventReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventReq.Unmarshal(m, b)
}
func (m *ListEventReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventReq.Marshal(b, m, deterministic)
}
func (m *ListEventReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventReq.Merge(m, src)
}
func (m *ListEventReq) XXX_Size() int {
	return xxx_messageInfo_ListEventReq.Size(m)
}
func (m *ListEventReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventReq proto.InternalMessageInfo

type ListEventRes struct {
	// Types that are valid to be assigned to Result:
	//	*ListEventRes_Events
	//	*ListEventRes_Error
	Result               isListEventRes_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListEventRes) Reset()         { *m = ListEventRes{} }
func (m *ListEventRes) String() string { return proto.CompactTextString(m) }
func (*ListEventRes) ProtoMessage()    {}
func (*ListEventRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d236019f42e23116, []int{11}
}

func (m *ListEventRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEventRes.Unmarshal(m, b)
}
func (m *ListEventRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEventRes.Marshal(b, m, deterministic)
}
func (m *ListEventRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEventRes.Merge(m, src)
}
func (m *ListEventRes) XXX_Size() int {
	return xxx_messageInfo_ListEventRes.Size(m)
}
func (m *ListEventRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEventRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListEventRes proto.InternalMessageInfo

type isListEventRes_Result interface {
	isListEventRes_Result()
}

type ListEventRes_Events struct {
	Events *EventList `protobuf:"bytes,1,opt,name=events,proto3,oneof"`
}

type ListEventRes_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListEventRes_Events) isListEventRes_Result() {}

func (*ListEventRes_Error) isListEventRes_Result() {}

func (m *ListEventRes) GetResult() isListEventRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ListEventRes) GetEvents() *EventList {
	if x, ok := m.GetResult().(*ListEventRes_Events); ok {
		return x.Events
	}
	return nil
}

func (m *ListEventRes) GetError() string {
	if x, ok := m.GetResult().(*ListEventRes_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ListEventRes) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ListEventRes_Events)(nil),
		(*ListEventRes_Error)(nil),
	}
}

func init() {
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*EventList)(nil), "event.EventList")
	proto.RegisterType((*CreateEventReq)(nil), "event.CreateEventReq")
	proto.RegisterType((*CreateEventRes)(nil), "event.CreateEventRes")
	proto.RegisterType((*UpdateEventReq)(nil), "event.UpdateEventReq")
	proto.RegisterType((*UpdateEventRes)(nil), "event.UpdateEventRes")
	proto.RegisterType((*DeleteEventReq)(nil), "event.DeleteEventReq")
	proto.RegisterType((*DeleteEventRes)(nil), "event.DeleteEventRes")
	proto.RegisterType((*GetEventReq)(nil), "event.GetEventReq")
	proto.RegisterType((*GetEventRes)(nil), "event.GetEventRes")
	proto.RegisterType((*ListEventReq)(nil), "event.ListEventReq")
	proto.RegisterType((*ListEventRes)(nil), "event.ListEventRes")
}

func init() { proto.RegisterFile("api/event.proto", fileDescriptor_d236019f42e23116) }

var fileDescriptor_d236019f42e23116 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x4b, 0xfb, 0x40,
	0x14, 0x6c, 0x92, 0x5f, 0x4b, 0xfb, 0x5a, 0xf2, 0x93, 0x27, 0x4a, 0x08, 0x0a, 0x21, 0xf4, 0x50,
	0x3c, 0x54, 0xac, 0xe2, 0xc5, 0x9b, 0x7f, 0xb0, 0x8a, 0xa7, 0x4a, 0xc1, 0x83, 0x97, 0x6a, 0xdf,
	0x21, 0xd0, 0xda, 0xb8, 0xbb, 0x16, 0xbf, 0x96, 0xdf, 0x50, 0xf6, 0x65, 0x1b, 0x37, 0x31, 0x2a,
	0x4a, 0x6f, 0xd9, 0xd9, 0x37, 0x3b, 0xb3, 0x3b, 0x43, 0xe0, 0xff, 0x24, 0x4d, 0xf6, 0x69, 0x49,
	0x4f, 0xaa, 0x9f, 0x8a, 0x85, 0x5a, 0x60, 0x9d, 0x17, 0xf1, 0x15, 0xd4, 0x2f, 0xf4, 0x07, 0xfa,
	0xe0, 0x26, 0xd3, 0xc0, 0x89, 0x9c, 0x9e, 0x37, 0x72, 0x93, 0x29, 0x22, 0xfc, 0x53, 0xf4, 0xaa,
	0x02, 0x37, 0x72, 0x7a, 0xad, 0x11, 0x7f, 0xe3, 0x0e, 0xb4, 0x54, 0x32, 0x27, 0xa9, 0x26, 0xf3,
	0x34, 0xf0, 0x78, 0xf4, 0x03, 0x88, 0x0f, 0xa0, 0xc5, 0x47, 0xdd, 0x24, 0x52, 0x61, 0x17, 0x1a,
	0x2c, 0x20, 0x03, 0x27, 0xf2, 0x7a, 0xed, 0x41, 0xa7, 0x9f, 0x89, 0xf3, 0xc4, 0xc8, 0xec, 0xc5,
	0x47, 0xe0, 0x9f, 0x09, 0x9a, 0x28, 0xca, 0x60, 0x7a, 0xc6, 0x18, 0x32, 0x63, 0xec, 0xa4, 0x4c,
	0x33, 0x9e, 0xef, 0x4a, 0x2c, 0x89, 0xdd, 0x6f, 0x58, 0xc3, 0x9a, 0xe1, 0xe1, 0x36, 0xd4, 0x49,
	0x88, 0x85, 0xc8, 0xee, 0xc4, 0xb8, 0x5e, 0x9e, 0x36, 0xa1, 0x21, 0x48, 0xbe, 0xcc, 0x94, 0xf6,
	0x33, 0x4e, 0xa7, 0x7f, 0xf0, 0x53, 0x60, 0xad, 0xcf, 0x4f, 0x04, 0xfe, 0x39, 0xcd, 0xc8, 0xf2,
	0x53, 0x8a, 0x29, 0xbe, 0x2e, 0x4d, 0x48, 0x3e, 0x35, 0xd7, 0xf6, 0x7e, 0xa3, 0xb6, 0x0b, 0xed,
	0x4b, 0x52, 0x5f, 0x4a, 0x8d, 0xed, 0xed, 0xf5, 0xdd, 0xd1, 0x87, 0x8e, 0x6e, 0xcc, 0x4a, 0x36,
	0xbe, 0x2f, 0xac, 0x25, 0xee, 0x59, 0x4d, 0xd2, 0x42, 0x1b, 0xb6, 0x90, 0x9e, 0x1c, 0xd6, 0x56,
	0x7d, 0xfa, 0x59, 0x6d, 0xf0, 0xe6, 0x42, 0x87, 0x99, 0xb7, 0x24, 0x96, 0xc9, 0x23, 0xe1, 0x09,
	0xb4, 0xad, 0x32, 0xe1, 0x96, 0x39, 0xbd, 0x58, 0xcb, 0xb0, 0x12, 0x96, 0x9a, 0x6c, 0x25, 0x9f,
	0x93, 0x8b, 0x1d, 0x0a, 0x2b, 0x61, 0x26, 0x5b, 0xd1, 0xe5, 0xe4, 0x62, 0xe0, 0x61, 0x25, 0x2c,
	0x71, 0x00, 0xcd, 0x55, 0x18, 0x88, 0x66, 0xc4, 0x0a, 0x2f, 0xfc, 0x8c, 0x49, 0x3c, 0x06, 0xc8,
	0x5f, 0x56, 0xe2, 0xa6, 0x99, 0xb0, 0x1f, 0x3f, 0xac, 0x00, 0xe5, 0x43, 0x83, 0xff, 0x18, 0x87,
	0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x58, 0xfa, 0x49, 0x44, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventServiceClient is the client API for EventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventServiceClient interface {
	CreateEvent(ctx context.Context, in *CreateEventReq, opts ...grpc.CallOption) (*CreateEventRes, error)
	UpdateEvent(ctx context.Context, in *UpdateEventReq, opts ...grpc.CallOption) (*UpdateEventRes, error)
	DeleteEvent(ctx context.Context, in *DeleteEventReq, opts ...grpc.CallOption) (*DeleteEventRes, error)
	GetEvent(ctx context.Context, in *GetEventReq, opts ...grpc.CallOption) (*GetEventRes, error)
	ListEvents(ctx context.Context, in *ListEventReq, opts ...grpc.CallOption) (*ListEventRes, error)
}

type eventServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventServiceClient(cc *grpc.ClientConn) EventServiceClient {
	return &eventServiceClient{cc}
}

func (c *eventServiceClient) CreateEvent(ctx context.Context, in *CreateEventReq, opts ...grpc.CallOption) (*CreateEventRes, error) {
	out := new(CreateEventRes)
	err := c.cc.Invoke(ctx, "/event.EventService/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventReq, opts ...grpc.CallOption) (*UpdateEventRes, error) {
	out := new(UpdateEventRes)
	err := c.cc.Invoke(ctx, "/event.EventService/UpdateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventReq, opts ...grpc.CallOption) (*DeleteEventRes, error) {
	out := new(DeleteEventRes)
	err := c.cc.Invoke(ctx, "/event.EventService/DeleteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) GetEvent(ctx context.Context, in *GetEventReq, opts ...grpc.CallOption) (*GetEventRes, error) {
	out := new(GetEventRes)
	err := c.cc.Invoke(ctx, "/event.EventService/GetEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventServiceClient) ListEvents(ctx context.Context, in *ListEventReq, opts ...grpc.CallOption) (*ListEventRes, error) {
	out := new(ListEventRes)
	err := c.cc.Invoke(ctx, "/event.EventService/ListEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServiceServer is the server API for EventService service.
type EventServiceServer interface {
	CreateEvent(context.Context, *CreateEventReq) (*CreateEventRes, error)
	UpdateEvent(context.Context, *UpdateEventReq) (*UpdateEventRes, error)
	DeleteEvent(context.Context, *DeleteEventReq) (*DeleteEventRes, error)
	GetEvent(context.Context, *GetEventReq) (*GetEventRes, error)
	ListEvents(context.Context, *ListEventReq) (*ListEventRes, error)
}

// UnimplementedEventServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventServiceServer struct {
}

func (*UnimplementedEventServiceServer) CreateEvent(ctx context.Context, req *CreateEventReq) (*CreateEventRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEvent not implemented")
}
func (*UnimplementedEventServiceServer) UpdateEvent(ctx context.Context, req *UpdateEventReq) (*UpdateEventRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (*UnimplementedEventServiceServer) DeleteEvent(ctx context.Context, req *DeleteEventReq) (*DeleteEventRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (*UnimplementedEventServiceServer) GetEvent(ctx context.Context, req *GetEventReq) (*GetEventRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvent not implemented")
}
func (*UnimplementedEventServiceServer) ListEvents(ctx context.Context, req *ListEventReq) (*ListEventRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}

func RegisterEventServiceServer(s *grpc.Server, srv EventServiceServer) {
	s.RegisterService(&_EventService_serviceDesc, srv)
}

func _EventService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).CreateEvent(ctx, req.(*CreateEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/UpdateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).UpdateEvent(ctx, req.(*UpdateEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).DeleteEvent(ctx, req.(*DeleteEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/GetEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).GetEvent(ctx, req.(*GetEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventService/ListEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServiceServer).ListEvents(ctx, req.(*ListEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventService",
	HandlerType: (*EventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventService_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _EventService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _EventService_DeleteEvent_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _EventService_GetEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _EventService_ListEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/event.proto",
}
