version: '2'

services:
  rest:
    image: egorzuev/rest_service:1.0.2
    ports:
      - "8082:8082"
    depends_on:
      - "db"
      - "queue"
    environment:
      - RPC_URI=rest:8082
      - QUEUE_URI=amqp://guest:guest@queue:5672
      - DB_URI=postgres://user:123@db:5432/otus
      - PROMETHEUS_URI=rest:8083
    command: ["./wait-for-it.sh", "db:5432", "queue:5672","--", "./service_rest", "grpc_server", "database"]
  scan:
    image: egorzuev/scan_service:1.0.1
    ports:
      - "8081:8081"
    depends_on:
      - "db"
      - "queue"
    environment:
      - QUEUE_URI=amqp://guest:guest@queue:5672
      - DB_URI=postgres://user:123@db:5432/otus
    command: ["./wait-for-it.sh", "db:5432", "queue:5672","--", "./service_scan", "scan", "30", "1539992129"]
  notification:
    image: egorzuev/notification_service:1.0.1
    ports:
      - "8080:8080"
    depends_on:
      - "queue"
      - "scan"
    environment:
      - QUEUE_URI=amqp://guest:guest@queue:5672
    command: ["./wait-for-it.sh", "queue:5672", "scan:8081","--", "./service_notification", "scan"]
  db:
    image: postgres:9.6
    container_name: "postgres_db"
    environment:
      - POSTGRES_DB=otus
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
  queue:
    image: rabbitmq:3.7
    container_name: "rabbitmq_queue"
    ports:
      - "5672:5672"
      - "15672:15672"
  db-exporter:
    image: wrouesnel/postgres_exporter:v0.4.1
    depends_on:
      - "db"
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=postgresql://user:123@db:5432/otus?sslmode=disable

  queue-exporter:
    image: kbudde/rabbitmq-exporter
    depends_on:
      - "queue"
    ports:
      - 9999:9090
    environment:
      RABBIT_URL: "http://queue:15672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      PUBLISH_PORT: "9090"
      OUTPUT_FORMAT: "JSON"
      LOG_LEVEL: "debug"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ${PWD}/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

#/etc/prometheus/prometheus.yml